version: '3.8'

services:
  db:
    image: postgres:14.7-alpine
    container_name: db
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "15432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
    container_name: monitoring-service
    depends_on:
      - db
    ports:
      - '8080:8080'
volumes:
  pgdata: