spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/postgres
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml